#!/usr/bin/env bash

set -e

echo "Updating package lists..."
sudo apt update

echo "Upgrading packages..."
sudo apt -y upgrade

echo "Removing unused packages..."
sudo apt -y autoremove

echo "Done."
